import { Prisma, Role, Severity } from '@prisma/client';
import prisma from '../../utils/prisma';
import { AppError } from '../../utils/AppError';
import { auditService } from '../../shared/audit/audit.service';

export type StaffActor={id:number;role:Role;departmentId:number;ipAddress?:string};
const CATEGORY_MAP:Record<string,string[]>={
  CLINICAL:['Medication Error','Patient Identification','Diagnosis or Treatment Delay','Procedure Complication','Other Clinical Event'],
  SAFETY:['Patient Fall','Staff Injury','Near Miss','Security Event','Other Safety Event'],
  EQUIPMENT:['Device Failure','Calibration Issue','Power or Battery Failure','Maintenance Issue','Other Equipment Event'],
  INFECTION_CONTROL:['Exposure','Isolation Breach','Sterilization Issue','Healthcare-Associated Infection','Other Infection Event'],
  FACILITY:['Fire or Alarm','Power Outage','Water or Environmental Hazard','Access or Security','Other Facility Event'],
  COMMUNICATION:['Handover Failure','Documentation Error','Escalation Delay','Miscommunication','Other Communication Event'],
  OTHER:['Other Reportable Event'],
};
const severityRank:Record<Severity,number>={LOW:1,MEDIUM:2,HIGH:3,CRITICAL:4};
const tokenize=(value:string)=>new Set(value.toLowerCase().replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(x=>x.length>2));
const similarity=(a:string,b:string)=>{const aa=tokenize(a),bb=tokenize(b);if(!aa.size||!bb.size)return 0;return [...aa].filter(x=>bb.has(x)).length/Math.sqrt(aa.size*bb.size)};
const snapshot=(incident:any)=>({title:incident.title,description:incident.description,severity:incident.severity,category:incident.category,subcategory:incident.subcategory,location:incident.location,departmentId:incident.departmentId,occurrenceAt:incident.occurrenceAt});

export class StaffService{
  private assertStaff(actor:StaffActor){if(actor.role!=='STAFF')throw new AppError('Staff access required.',403)}
  private async owned(id:number,actor:StaffActor){this.assertStaff(actor);const item=await prisma.incident.findFirst({where:{id,reporterId:actor.id},include:{department:true,attachments:true,actionItems:{select:{id:true,title:true,status:true,reviewStatus:true,createdAt:true,updatedAt:true}},reviews:{select:{id:true,outcome:true,reviewedAt:true}},investigationRecord:{select:{status:true,submittedAt:true,approvedAt:true,createdAt:true,updatedAt:true}},staffVersions:{orderBy:{version:'desc'}}}});if(!item)throw new AppError('Incident not found or it was not reported by you.',403);return item}
  async config(){return {categories:CATEGORY_MAP,departments:await prisma.department.findMany({where:{isActive:true},select:{id:true,name:true,description:true},orderBy:{name:'asc'}})}}
  async list(actor:StaffActor,q:any){this.assertStaff(actor);const where:Prisma.IncidentWhereInput={reporterId:actor.id,status:q.status,severity:q.severity,category:q.category,reportedAt:q.from||q.to?{gte:q.from,lte:q.to}:undefined,OR:q.search?[{referenceId:{contains:q.search,mode:'insensitive'}},{title:{contains:q.search,mode:'insensitive'}},{description:{contains:q.search,mode:'insensitive'}},{location:{contains:q.search,mode:'insensitive'}}]:undefined};const items=await prisma.incident.findMany({where,include:{department:{select:{id:true,name:true}},_count:{select:{attachments:true}}},orderBy:{reportedAt:'desc'}});const all=await prisma.incident.findMany({where:{reporterId:actor.id},select:{status:true}});return {items,summary:{total:all.length,open:all.filter(x=>x.status==='OPEN').length,inProgress:all.filter(x=>['ACCEPTED','INVESTIGATING','PENDING_ACTION','UNDER_REVIEW'].includes(x.status)).length,rejected:all.filter(x=>x.status==='REJECTED').length,closed:all.filter(x=>x.status==='CLOSED').length}}}
  async detail(id:number,actor:StaffActor){const item=await this.owned(id,actor);const timeline:any[]=[{key:'submitted',type:'SUBMITTED',title:'Incident submitted',at:item.reportedAt,detail:`Reference ${item.referenceId}`}];if(item.managerDecisionType)timeline.push({key:'decision',type:item.managerDecisionType,title:item.managerDecisionType==='REQUEST_REVISION'?'Revision requested':`Manager ${item.managerDecisionType.toLowerCase()}`,at:item.managerDecisionAt??item.updatedAt,detail:item.managerDecisionComment});if(item.investigatorId)timeline.push({key:'investigation',type:'INVESTIGATION',title:'Investigation assigned',at:item.investigationRecord?.createdAt??item.updatedAt,detail:'The department investigation is in progress.'});if(item.investigationRecord?.submittedAt)timeline.push({key:'findings',type:'INVESTIGATION_SUBMITTED',title:'Investigation findings submitted',at:item.investigationRecord.submittedAt,detail:'Findings are awaiting authorized review.'});item.actionItems.forEach(a=>timeline.push({key:`action-${a.id}`,type:'ACTION',title:`Action: ${a.title}`,at:a.createdAt,detail:a.reviewStatus==='VERIFIED'?'Action verified.':`Current state: ${a.status.replaceAll('_',' ')}`}));item.reviews.forEach(r=>timeline.push({key:`review-${r.id}`,type:'REVIEW',title:'Management review recorded',at:r.reviewedAt,detail:`Outcome: ${r.outcome.replaceAll('_',' ')}`}));if(item.closedAt)timeline.push({key:'closed',type:'CLOSED',title:'Incident closed',at:item.closedAt,detail:'The authorized workflow is complete.'});timeline.sort((a,b)=>new Date(a.at).getTime()-new Date(b.at).getTime());const notifications=timeline.filter(x=>['REQUEST_REVISION','REJECT','ACCEPT','CLOSED'].includes(x.type)).map(x=>({...x,read:false}));return {...item,timeline,notifications,statusExplanation:this.statusExplanation(item.status,item.managerDecisionType)}}
  private statusExplanation(status:string,decision:string|null){if(decision==='REQUEST_REVISION')return 'Your Manager requested changes. Update only the listed fields and resubmit.';return ({OPEN:'Submitted and waiting for Manager triage.',ACCEPTED:'Accepted and waiting for investigator assignment.',REJECTED:'The Manager rejected this report; review the decision comment.',INVESTIGATING:'An authorized investigation is in progress.',PENDING_ACTION:'Investigation is approved and corrective actions are being managed.',UNDER_REVIEW:'Management review is in progress.',CLOSED:'The incident workflow has been completed.'} as any)[status]??'Workflow status updated.'}
  async draft(actor:StaffActor){this.assertStaff(actor);return prisma.staffIncidentDraft.findUnique({where:{reporterId:actor.id}})}
  async saveDraft(input:any,actor:StaffActor){this.assertStaff(actor);if(input.departmentId){const department=await prisma.department.findFirst({where:{id:input.departmentId,isActive:true}});if(!department)throw new AppError('Select an active department.',400)}return prisma.staffIncidentDraft.upsert({where:{reporterId:actor.id},update:input,create:{...input,reporterId:actor.id}})}
  async deleteDraft(actor:StaffActor){this.assertStaff(actor);await prisma.staffIncidentDraft.deleteMany({where:{reporterId:actor.id}});return {deleted:true}}
  private validateSubmission(input:any){const choices=CATEGORY_MAP[input.category];if(!choices||!choices.includes(input.subcategory))throw new AppError('Select an approved sub-category for the chosen category.',400);if(input.occurrenceAt>new Date())throw new AppError('Occurrence date and time cannot be in the future.',400)}
  async submit(input:any,files:Express.Multer.File[],actor:StaffActor){this.assertStaff(actor);this.validateSubmission(input);const department=await prisma.department.findFirst({where:{id:input.departmentId,isActive:true}});if(!department)throw new AppError('Only active departments can receive incident reports.',400);const incident=await prisma.$transaction(async tx=>{const created=await tx.incident.create({data:{title:input.title,description:input.description,severity:input.severity,category:input.category,subcategory:input.subcategory,location:input.location,occurrenceAt:input.occurrenceAt,reportedAt:new Date(),departmentId:input.departmentId,reporterId:actor.id,status:'OPEN'}});const referenceId=`HIMS-${created.reportedAt.getUTCFullYear()}-${String(created.id).padStart(6,'0')}`;const updated=await tx.incident.update({where:{id:created.id},data:{referenceId}});if(files?.length)await tx.incidentAttachment.createMany({data:files.map(file=>({incidentId:created.id,fileName:file.originalname,filePath:file.path,fileType:file.mimetype}))});await tx.staffIncidentVersion.create({data:{incidentId:created.id,version:1,snapshot:snapshot(updated)}});await tx.staffIncidentDraft.deleteMany({where:{reporterId:actor.id}});return updated});await auditService.record({actorId:actor.id,actorRole:actor.role,eventType:'STAFF_REPORTING',action:'SUBMIT_INCIDENT',entityType:'INCIDENT',entityId:incident.id,departmentId:incident.departmentId,after:incident,ipAddress:actor.ipAddress});return incident}
  async resubmit(id:number,input:{changes:Record<string,unknown>;responseNote:string},actor:StaffActor){const current=await this.owned(id,actor);if(current.managerDecisionType!=='REQUEST_REVISION'||current.status!=='OPEN')throw new AppError('This incident is not open for Staff revision.',409);const allowed=new Set(current.revisionFields);const keys=Object.keys(input.changes);if(!keys.length||keys.some(key=>!allowed.has(key)))throw new AppError('Only fields requested by the Manager may be changed.',403);const changes:any={...input.changes};if(changes.departmentId){const dept=await prisma.department.findFirst({where:{id:Number(changes.departmentId),isActive:true}});if(!dept)throw new AppError('Select an active department.',400);changes.departmentId=Number(changes.departmentId)}if(changes.occurrenceAt)changes.occurrenceAt=new Date(String(changes.occurrenceAt));const merged={...current,...changes};this.validateSubmission(merged);const version=current.staffRevisionNumber+2;const updated=await prisma.$transaction(async tx=>{await tx.staffIncidentVersion.create({data:{incidentId:id,version,snapshot:snapshot(merged),changeReason:input.responseNote}});return tx.incident.update({where:{id},data:{...changes,managerDecisionType:'RESUBMITTED',managerDecisionAt:new Date(),staffRevisionNumber:{increment:1},revisionFields:[]}})});await auditService.record({actorId:actor.id,actorRole:actor.role,eventType:'STAFF_REPORTING',action:'RESUBMIT_REVISION',entityType:'INCIDENT',entityId:id,departmentId:updated.departmentId,before:current,after:updated,metadata:{responseNote:input.responseNote,fields:keys},ipAddress:actor.ipAddress});return updated}
  async assist(input:any,actor:StaffActor){this.assertStaff(actor);const text=`${input.title??''} ${input.description??''} ${input.location??''}`.toLowerCase();const categoryScores=Object.keys(CATEGORY_MAP).map(category=>{const keys=({CLINICAL:['patient','medication','dose','treatment','procedure'],SAFETY:['fall','injury','hazard','near miss'],EQUIPMENT:['device','machine','equipment','battery','calibration'],INFECTION_CONTROL:['infection','exposure','sterile','isolation'],FACILITY:['fire','alarm','power','water','building'],COMMUNICATION:['handover','communication','document','message'],OTHER:[]} as any)[category];return {category,score:keys.filter((k:string)=>text.includes(k)).length}}).sort((a,b)=>b.score-a.score);const suggestedCategory=categoryScores[0].score?categoryScores[0].category:(input.category||'OTHER');const critical=['death','cardiac arrest','sentinel','life threatening'];const high=['serious harm','fracture','wrong dose','fire','power outage'];const medium=['injury','delay','failure','fall'];const suggestedSeverity=critical.some(x=>text.includes(x))?'CRITICAL':high.some(x=>text.includes(x))?'HIGH':medium.some(x=>text.includes(x))?'MEDIUM':'LOW';const missing:string[]=[];if(!input.occurrenceAt)missing.push('occurrence date and time');if(!input.location?.trim())missing.push('exact location');if(!input.category)missing.push('category');if(!input.subcategory)missing.push('sub-category');if((input.description??'').trim().length<30)missing.push('clear chronology and immediate response');const candidates=await prisma.incident.findMany({where:{description:{not:''}},select:{title:true,description:true,category:true,severity:true},take:300});const source=`${input.title??''} ${input.description??''}`;const similar=candidates.map(x=>({score:similarity(source,`${x.title} ${x.description}`),category:x.category,severity:x.severity})).filter(x=>x.score>=.25).sort((a,b)=>b.score-a.score);const summary=(input.description??'').trim().split(/(?<=[.!?])\s+/).slice(0,2).join(' ');return {modelVersion:'staff-assistance-local-v1.0',category:{value:suggestedCategory,subcategories:CATEGORY_MAP[suggestedCategory],reason:`Matched report language to the approved ${suggestedCategory.replaceAll('_',' ').toLowerCase()} classification.`},severity:{value:suggestedSeverity,reason:`Starting level based on harm and urgency terms; you must confirm or change it.`},duplicates:{possible:similar.length>0,count:similar.length,highestSimilarity:similar[0]?.score??0,notice:similar.length?'A potentially similar report exists. No other reporter or incident details are exposed; you may continue with a reason.':'No strong similarity notice was found.'},completeness:{score:Math.max(0,100-missing.length*18),missing},summary:{title:(input.title??'').trim()||'Safety incident report',text:summary||'Add a clear chronology to generate an editable summary.'},disclaimer:'Suggestions support Staff judgment and are never submitted or finalized automatically.'}}
  async feedback(input:any,actor:StaffActor){this.assertStaff(actor);return prisma.staffAiFeedback.create({data:{reporterId:actor.id,feature:input.feature,suggestion:input.suggestion as Prisma.InputJsonValue,action:input.action,reason:input.reason}})}
}
export const staffService=new StaffService();
