import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { actionOwnerApi } from '../api/actionOwner.api';

const ORANGE='#E77900',DARK='#7C3D00',BORDER='#FED7AA',TEXT='#1F2937',MUTED='#6B7280';
export const ActionOwnerDashboard=()=>{
  const nav=useNavigate(); const [search,setSearch]=useState(''); const [status,setStatus]=useState(''); const [priority,setPriority]=useState(''); const [due,setDue]=useState('ALL');
  const params=Object.fromEntries(Object.entries({search,status,priority,due}).filter(([,v])=>v));
  const {data,isLoading,isError}=useQuery({queryKey:['action-owner-dashboard',params],queryFn:()=>actionOwnerApi.dashboard(params)});
  if(isLoading)return <div className="h-80 grid place-items-center font-bold" style={{color:ORANGE}}>Loading assigned actions…</div>;
  return <div className="space-y-6 pb-8">
    <header className="rounded-2xl p-7 text-white flex flex-col xl:flex-row xl:items-end justify-between gap-5" style={{background:`linear-gradient(135deg,${DARK},${ORANGE})`,boxShadow:'0 7px 26px rgba(231,121,0,.22)'}}><div><div className="text-xs uppercase tracking-[.2em] font-bold opacity-75">Assignment-scoped delivery workspace</div><h1 className="text-3xl font-extrabold mt-2">Action Owner Dashboard</h1><p className="mt-1 opacity-85">Complete assigned corrective actions, attach evidence, and respond to Manager verification.</p></div><div className="grid grid-cols-5 gap-2">{[['Total',data?.summary.total],['Not Started',data?.summary.open],['In Progress',data?.summary.inProgress],['Overdue',data?.summary.overdue],['Revision',data?.summary.revisions]].map(([k,v])=><div key={k} className="rounded-xl px-3 py-2 bg-white/15 text-center min-w-20"><div className="text-xl font-extrabold">{v??0}</div><div className="text-[10px] uppercase font-bold opacity-75">{k}</div></div>)}</div></header>
    {!!data?.notifications.filter(n=>!n.readAt).length&&<section className="rounded-2xl bg-amber-50 border border-amber-300 p-4"><b className="text-amber-900">Notifications ({data.notifications.filter(n=>!n.readAt).length})</b><div className="mt-2 flex flex-wrap gap-2">{data.notifications.filter(n=>!n.readAt).slice(0,4).map(n=><button key={n.id} onClick={()=>nav(`/action-owner/${n.actionId}`)} className="rounded-lg bg-white px-3 py-2 text-xs text-left border border-amber-200"><b>{n.title}</b> — {n.message}</button>)}</div></section>}
    <section className="rounded-2xl bg-white p-5 grid md:grid-cols-2 xl:grid-cols-4 gap-3" style={{border:`1.5px solid ${BORDER}`}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search action or incident…" className="px-4 py-3 rounded-xl border border-orange-200 outline-orange-500"/><select value={status} onChange={e=>setStatus(e.target.value)} className="px-3 py-3 rounded-xl border border-orange-200"><option value="">All progress states</option><option value="OPEN">Not Started</option><option value="IN_PROGRESS">In Progress</option><option value="COMPLETED">Completed</option></select><select value={priority} onChange={e=>setPriority(e.target.value)} className="px-3 py-3 rounded-xl border border-orange-200"><option value="">All priorities</option>{['LOW','MEDIUM','HIGH','CRITICAL'].map(v=><option key={v}>{v}</option>)}</select><select value={due} onChange={e=>setDue(e.target.value)} className="px-3 py-3 rounded-xl border border-orange-200"><option value="ALL">All due dates</option><option value="DUE_SOON">Due in 3 days</option><option value="OVERDUE">Overdue</option></select></section>
    <section className="rounded-2xl bg-white overflow-hidden" style={{border:`1.5px solid ${BORDER}`}}><div className="p-5 border-b border-orange-100"><h2 className="text-lg font-extrabold" style={{color:TEXT}}>Assigned Action Queue</h2><p className="text-sm" style={{color:MUTED}}>This API returns only action records explicitly assigned to your account.</p></div>{isError?<div className="p-12 text-center text-red-600">Unable to load assigned actions.</div>:!data?.items.length?<div className="p-16 text-center text-slate-500">No assigned actions match these filters.</div>:<div className="divide-y divide-orange-100">{data.items.map(item=><button key={item.id} onClick={()=>nav(`/action-owner/${item.id}`)} className="w-full text-left p-5 hover:bg-orange-50 grid lg:grid-cols-[1fr_auto] gap-4"><div><div className="flex flex-wrap gap-2 items-center"><b className="text-base" style={{color:TEXT}}>#{item.id} {item.title}</b><span className="px-2 py-1 rounded-md text-xs font-bold bg-orange-100 text-orange-800">{item.status==='OPEN'?'NOT STARTED':item.status.replaceAll('_',' ')}</span><span className="px-2 py-1 rounded-md text-xs font-bold bg-slate-100">{item.type}</span>{item.overdue&&<span className="px-2 py-1 rounded-md text-xs font-bold bg-red-100 text-red-700">OVERDUE</span>}{item.reviewStatus==='RETURNED_FOR_REVISION'&&<span className="px-2 py-1 rounded-md text-xs font-bold bg-amber-100 text-amber-800">REVISION REQUIRED</span>}</div><p className="text-sm mt-2" style={{color:MUTED}}>Incident #{item.incident.id}: {item.incident.title} • {item.incident.department.name}</p><p className="text-xs mt-2 text-slate-500 line-clamp-2">{item.description}</p></div><div className="lg:text-right"><b style={{color:item.priority==='CRITICAL'?'#DC2626':ORANGE}}>{item.priority}</b><div className="text-xs text-slate-500 mt-1">Due {new Date(item.dueDate).toLocaleDateString()} ({item.dueInDays}d)</div><div className="text-xs font-bold mt-2">Risk {item.completionRisk.score}% • {item.completionRisk.level}</div></div></button>)}</div>}</section>
  </div>;
};
export default ActionOwnerDashboard;
