import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { investigationApi } from '../api/investigation.api';

const PURPLE='#2952C4', BORDER='#D8DCE8', TEXT='#1A2447', MUTED='#6B7494';
const InvestigatorDashboard=()=>{
  const navigate=useNavigate(); const [search,setSearch]=useState(''); const [status,setStatus]=useState(''); const [severity,setSeverity]=useState(''); const [due,setDue]=useState('');
  const params=Object.fromEntries(Object.entries({search,status,severity,due}).filter(([,v])=>v));
  const {data,isLoading,isError}=useQuery({queryKey:['investigation-dashboard',params],queryFn:()=>investigationApi.dashboard(params)});
  if(isLoading)return <div className="h-80 grid place-items-center font-bold" style={{color:PURPLE}}>Loading assigned investigations…</div>;
  return <div className="space-y-6 pb-6">
    <header className="rounded-2xl border border-white/15 bg-[var(--k-navy)] p-7 text-white shadow-lg flex flex-col lg:flex-row lg:items-end justify-between gap-5"><div><div className="text-xs uppercase tracking-[.16em] font-bold opacity-75">Investigation workspace</div><h1 className="text-3xl font-extrabold mt-2">Investigator Dashboard</h1><p className="mt-1 opacity-80">Review assigned cases, save a draft, and submit findings for Manager review.</p></div><div className="grid grid-cols-5 gap-2">{[['Total',data?.summary.total],['Drafts',data?.summary.drafts],['Revision',data?.summary.revision],['Submitted',data?.summary.submitted],['Overdue',data?.summary.overdue]].map(([k,v])=><div key={k} className="rounded-xl px-3 py-2 bg-white/15 text-center"><div className="text-xl font-extrabold">{v??0}</div><div className="text-[10px] uppercase font-bold opacity-70">{k}</div></div>)}</div></header>
    <section className="rounded-2xl bg-white p-5 grid md:grid-cols-2 xl:grid-cols-4 gap-3" style={{border:`1.5px solid ${BORDER}`}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search title, category or location…" className="px-4 py-3 rounded-xl border border-violet-200 outline-violet-600"/><select value={status} onChange={e=>setStatus(e.target.value)} className="px-3 py-3 rounded-xl border border-violet-200"><option value="">All investigation states</option>{['DRAFT','REVISION_REQUESTED','SUBMITTED','APPROVED'].map(v=><option key={v}>{v}</option>)}</select><select value={severity} onChange={e=>setSeverity(e.target.value)} className="px-3 py-3 rounded-xl border border-violet-200"><option value="">All severities</option>{['LOW','MEDIUM','HIGH','CRITICAL'].map(v=><option key={v}>{v}</option>)}</select><select value={due} onChange={e=>setDue(e.target.value)} className="px-3 py-3 rounded-xl border border-violet-200"><option value="">All due dates</option><option value="OVERDUE">Overdue</option><option value="NEXT_7_DAYS">Next 7 days</option><option value="NO_DATE">No target date</option></select></section>
    <section className="rounded-2xl bg-white overflow-hidden" style={{border:`1.5px solid ${BORDER}`}}><div className="p-5 border-b border-violet-100"><h2 className="text-lg font-extrabold" style={{color:TEXT}}>Assigned Investigation Queue</h2><p className="text-sm" style={{color:MUTED}}>Cases currently assigned to you.</p></div>{isError?<div className="p-12 text-center text-red-600">Unable to load assigned investigations.</div>:!data?.items.length?<div className="p-16 text-center text-slate-500">No assigned cases match these filters.</div>:<div className="divide-y divide-violet-100">{data.items.map(item=><button key={item.id} onClick={()=>navigate(`/investigator/${item.incidentId}`)} className="w-full text-left p-5 hover:bg-violet-50 grid md:grid-cols-[1fr_auto] gap-4"><div><div className="flex flex-wrap items-center gap-2"><b className="text-base" style={{color:TEXT}}>#{item.incidentId} {item.incident.title}</b><span className="px-2 py-1 rounded-md text-xs font-bold text-violet-700 bg-violet-100">{item.status.replaceAll('_',' ')}</span>{item.overdue&&<span className="px-2 py-1 rounded-md text-xs font-bold text-red-700 bg-red-100">OVERDUE</span>}</div><p className="text-sm mt-2" style={{color:MUTED}}>{item.incident.category} • {item.incident.location} • {item.incident.department?.name}</p><div className="flex flex-wrap gap-3 mt-3 text-xs text-slate-500"><span>Team {item._count.teamMembers}</span><span>Factors {item._count.contributingFactors}</span><span>Evidence {item._count.evidence}</span><span>Timeline {item._count.timeline}</span><span>Revision {item.revisionNumber}</span></div></div><div className="md:text-right"><div className="font-extrabold" style={{color:item.incident.severity==='CRITICAL'?'#DC2626':PURPLE}}>{item.incident.severity}</div><div className="text-xs mt-1 text-slate-500">Target: {item.endDate?new Date(item.endDate).toLocaleDateString():'Not set'}</div></div></button>)}</div>}</section>
  </div>;
};
export default InvestigatorDashboard;
