import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useAuthContext } from '../context/AuthContext';
import { managerApi } from '../api/manager.api';

const NAVY = '#1E2B5E'; const BLUE = '#2952C4'; const BORDER = '#D8DCE8'; const TEXT = '#1A2447'; const MUTED = '#6B7494';
const colors = ['#2952C4', '#8B5CF6', '#F59E0B', '#EF4444', '#10B981'];
const Panel = ({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) => <section className="rounded-2xl p-5 bg-white" style={{ border: `1.5px solid ${BORDER}`, boxShadow: '0 2px 8px rgba(30,43,94,.06)' }}><h2 className="text-lg font-extrabold" style={{ color: TEXT }}>{title}</h2>{subtitle && <p className="text-xs mt-1 mb-4" style={{ color: MUTED }}>{subtitle}</p>}{children}</section>;

export const ManagerDashboard: React.FC = () => {
  const { user } = useAuthContext(); const navigate = useNavigate();
  const { data, isLoading, error } = useQuery({ queryKey: ['manager-dashboard'], queryFn: managerApi.dashboard });
  if (isLoading) return <div className="h-80 grid place-items-center text-blue-700 font-bold">Loading department risk dashboard…</div>;
  if (!data || error) return <div className="p-6 rounded-xl bg-red-50 text-red-700">Could not load the Manager dashboard.</div>;
  const cards = [['Submitted', data.summary.submitted, '#2563EB', 'Needs manager decision'], ['Investigating', data.summary.investigating, '#7C3AED', 'Root-cause work in progress'], ['Action overdue', data.summary.actionOverdue, '#DC2626', 'Past due and incomplete'], ['Review pending', data.summary.reviewPending, '#D97706', 'Human approval required'], ['High risk', data.summary.highRisk, '#EA580C', 'High or critical exposure'], ['Closed', data.summary.closed, '#16A34A', 'Structured closure complete']] as const;
  return <div className="space-y-6 pb-5">
    <header className="rounded-2xl p-7 flex flex-col md:flex-row justify-between gap-5 text-white" style={{ background: `linear-gradient(135deg,${NAVY},#1B367A)`, boxShadow: '0 6px 28px rgba(30,43,94,.22)' }}><div><div className="text-xs tracking-widest font-bold uppercase opacity-75">Department risk & workflow • Real-time</div><h1 className="text-3xl font-extrabold mt-2">Manager Dashboard</h1><p className="mt-1 opacity-80">Welcome back, <b>{user?.name}</b>. Decisions and analytics are limited to your department.</p></div><button onClick={() => navigate('/incidents')} className="self-center px-5 py-3 rounded-xl font-bold bg-blue-600 hover:bg-blue-700">Review incident queue →</button></header>
    <div className="grid sm:grid-cols-2 xl:grid-cols-6 gap-4">{cards.map(([label,value,color,sub]) => <button key={label} onClick={() => navigate('/incidents')} className="text-left rounded-2xl p-5 bg-white hover:-translate-y-0.5 transition" style={{ border: `1.5px solid ${BORDER}` }}><div className="text-xs uppercase tracking-wider font-bold" style={{ color: MUTED }}>{label}</div><div className="text-3xl font-extrabold my-2" style={{ color }}>{value}</div><div className="text-xs" style={{ color: MUTED }}>{sub}</div></button>)}</div>
    <div className="grid xl:grid-cols-2 gap-6">
      <Panel title="Incident Frequency Trends" subtitle="Daily incident volume for your department"><div className="h-64"><ResponsiveContainer><LineChart data={data.frequencyTrend}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" fontSize={11}/><YAxis allowDecimals={false}/><Tooltip/><Line type="monotone" dataKey="value" stroke={BLUE} strokeWidth={3}/></LineChart></ResponsiveContainer></div></Panel>
      <Panel title="Root Cause Distribution" subtitle="Approved RCA categories and emerging patterns"><div className="h-64"><ResponsiveContainer><BarChart data={data.rootCauseDistribution}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" fontSize={11}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" radius={[6,6,0,0]}>{data.rootCauseDistribution.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Bar></BarChart></ResponsiveContainer></div></Panel>
      <Panel title="Control Effectiveness Heatmap" subtitle="Repeatedly ineffective control classifications"><div className="grid grid-cols-2 gap-3 mt-5">{data.controlEffectiveness.length ? data.controlEffectiveness.map((item,i)=><div key={item.name} className="rounded-xl p-4 text-white" style={{ background: colors[i%colors.length] }}><div className="text-xs font-bold">{item.name.replaceAll('_',' ')}</div><div className="text-3xl font-extrabold">{item.value}</div></div>):<p className="text-sm text-slate-500">No control assessments recorded yet.</p>}</div></Panel>
      <Panel title="Resolution & Open Incident Ageing" subtitle={`Average resolution: ${data.averageResolutionHours.toFixed(1)} hours`}><div className="space-y-3 mt-5">{data.ageing.map((item,i)=><div key={item.name}><div className="flex justify-between text-sm font-bold"><span>{item.name}</span><span>{item.value}</span></div><div className="h-3 rounded-full bg-slate-100 mt-1"><div className="h-full rounded-full" style={{ width: `${Math.max(4, Math.min(100,item.value*12))}%`, background: colors[i] }}/></div></div>)}</div></Panel>
    </div>
    <div className="grid lg:grid-cols-3 gap-6">
      <Panel title="Submitted incidents"><div className="space-y-2 mt-4">{data.queues.submitted.length ? data.queues.submitted.map((item)=><button key={item.id} onClick={()=>navigate(`/incidents/${item.id}`)} className="w-full text-left p-3 rounded-xl bg-slate-50 hover:bg-blue-50"><b>#{item.id} {item.title}</b><div className="text-xs text-slate-500 mt-1">{item.severity} • {item.status}</div></button>):<p className="text-sm text-slate-500">Queue is clear.</p>}</div></Panel>
      <Panel title="Review pending"><div className="space-y-2 mt-4">{data.queues.reviewPending.length ? data.queues.reviewPending.map((item)=><button key={item.id} onClick={()=>navigate(`/incidents/${item.id}`)} className="w-full text-left p-3 rounded-xl bg-slate-50 hover:bg-blue-50"><b>#{item.id} {item.title}</b><div className="text-xs text-slate-500 mt-1">Human approval required</div></button>):<p className="text-sm text-slate-500">Queue is clear.</p>}</div></Panel>
      <Panel title="Overdue Actions"><div className="space-y-2 mt-4">{data.queues.overdueActions.length ? data.queues.overdueActions.map((item)=><div key={item.id} className="p-3 rounded-xl bg-red-50"><b>{item.title}</b><div className="text-xs text-red-700 mt-1">{item.priority} • due {new Date(item.dueDate).toLocaleDateString()}</div></div>):<p className="text-sm text-slate-500">No overdue actions.</p>}</div></Panel>
    </div>
  </div>;
};
