import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { PlusCircle } from 'lucide-react';
import { staffApi } from '../api/staff.api';
const TEAL='#2952C4',DARK='#1E2B5E',BORDER='#D8DCE8',TEXT='#1A2447',MUTED='#6B7494';
const MyIncidentsPage=()=>{const nav=useNavigate();const[search,setSearch]=useState('');const[status,setStatus]=useState('');const[severity,setSeverity]=useState('');const[category,setCategory]=useState('');const[from,setFrom]=useState('');const[to,setTo]=useState('');const params=Object.fromEntries(Object.entries({search,status,severity,category,from,to}).filter(([,v])=>v));const{data,isLoading,isError}=useQuery({queryKey:['staff-incidents',params],queryFn:()=>staffApi.list(params)});const{data:config}=useQuery({queryKey:['staff-config'],queryFn:staffApi.config});if(isLoading)return <div className="h-80 grid place-items-center font-bold" style={{color:TEAL}}>Loading your incident reports…</div>;return <div className="space-y-6 pb-8">
  <header className="rounded-2xl border border-white/15 bg-[var(--k-navy)] p-7 text-white shadow-lg flex flex-col lg:flex-row lg:items-end justify-between gap-5"><div><div className="text-xs uppercase tracking-[.16em] font-bold opacity-75">Incident reporting</div><h1 className="text-3xl font-extrabold mt-2">My Incidents</h1><p className="mt-1 opacity-85">Track your submitted reports and respond to any revision request.</p></div><button onClick={()=>nav('/submit-incident')} className="rounded-xl bg-white px-4 py-3 font-bold flex items-center gap-2" style={{color:DARK}}><PlusCircle size={18}/> Report an incident</button></header>
  <div className="grid grid-cols-2 lg:grid-cols-5 gap-3">{[['Total',data?.summary.total,'#0F8278'],['Awaiting Triage',data?.summary.open,'#2563EB'],['In Progress',data?.summary.inProgress,'#D97706'],['Rejected',data?.summary.rejected,'#DC2626'],['Closed',data?.summary.closed,'#16A34A']].map(([k,v,c])=><div key={k} className="rounded-xl bg-white p-4" style={{border:`1px solid ${BORDER}`}}><div className="text-xs uppercase font-bold" style={{color:MUTED}}>{k}</div><div className="text-3xl font-extrabold mt-1" style={{color:String(c)}}>{v??0}</div></div>)}</div>
  <section className="rounded-2xl bg-white p-4 grid md:grid-cols-2 xl:grid-cols-6 gap-3" style={{border:`1px solid ${BORDER}`}}><input aria-label="Search my incidents" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search ID, title, text or location" className="xl:col-span-2 rounded-xl border border-teal-200 px-3 py-2.5 outline-teal-600"/><select aria-label="Filter status" value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-teal-200 px-3"><option value="">All statuses</option>{['OPEN','ACCEPTED','REJECTED','INVESTIGATING','PENDING_ACTION','UNDER_REVIEW','CLOSED'].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Filter severity" value={severity} onChange={e=>setSeverity(e.target.value)} className="rounded-xl border border-teal-200 px-3"><option value="">All severities</option>{['LOW','MEDIUM','HIGH','CRITICAL'].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Filter category" value={category} onChange={e=>setCategory(e.target.value)} className="rounded-xl border border-teal-200 px-3"><option value="">All categories</option>{Object.keys(config?.categories??{}).map(x=><option key={x}>{x}</option>)}</select><div className="grid grid-cols-2 gap-1"><input aria-label="From date" type="date" value={from} onChange={e=>setFrom(e.target.value)} className="min-w-0 rounded-lg border border-teal-200 px-1"/><input aria-label="To date" type="date" value={to} onChange={e=>setTo(e.target.value)} className="min-w-0 rounded-lg border border-teal-200 px-1"/></div></section>
  <section className="rounded-2xl bg-white overflow-hidden" style={{border:`1px solid ${BORDER}`}}><div className="p-5 border-b border-teal-100"><h2 className="font-extrabold" style={{color:TEXT}}>Owned Incident Register</h2><p className="text-sm" style={{color:MUTED}}>Counts and cards come from an authenticated own-incidents API.</p></div>{isError?<div className="p-12 text-center text-red-600">Unable to load your incident reports.</div>:!data?.items.length?<div className="p-16 text-center text-slate-500">No reports match these filters.</div>:<div className="divide-y divide-teal-100">{data.items.map(item=><button key={item.id} onClick={()=>nav(`/my-incidents/${item.id}`)} className="w-full text-left p-5 hover:bg-teal-50 grid lg:grid-cols-[1fr_auto] gap-4"><div><div className="flex flex-wrap items-center gap-2"><b style={{color:TEXT}}>{item.referenceId} • {item.title}</b><span className="rounded-md bg-teal-100 px-2 py-1 text-xs font-bold text-teal-800">{item.status.replaceAll('_',' ')}</span>{item.managerDecisionType==='REQUEST_REVISION'&&<span className="rounded-md bg-amber-100 px-2 py-1 text-xs font-bold text-amber-800">REVISION REQUESTED</span>}</div><p className="text-sm mt-2" style={{color:MUTED}}>{item.category} / {item.subcategory} • {item.location} • {item.department.name}</p><p className="text-xs mt-2 text-slate-500">Occurred {new Date(item.occurrenceAt).toLocaleString()} • Reported {new Date(item.reportedAt).toLocaleString()} • {item._count?.attachments??0} evidence file(s)</p></div><div className="lg:text-right"><b style={{color:item.severity==='CRITICAL'?'#DC2626':TEAL}}>{item.severity}</b><p className="text-xs mt-1 text-slate-500">Updated {new Date(item.updatedAt).toLocaleDateString()}</p></div></button>)}</div>}</section>
 </div>};
export default MyIncidentsPage;
